#baseURL: 'https://jtom38.github.io/cookbook/'
baseURL: 'https://cookbook.jamestombleson.com/'
languageCode: 'en-us'
title: 'Tombleson Family Cookbook'
theme: "hugo-bulma-cookbook"

taxonomies:
  category: 'categories'
  tag: 'tags'

# Used to bring the /tags/ forward
preserveTaxonomyNames: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  # This tells hugp-bulma-cookbook theme to use the list display view
  UseListRows: true

  # Enable this line to use the card view
  #UseCardView: true