baseURL: 'https://jtom38.github.io/cookbook/'
languageCode: 'en-us'
title: 'Tombleson Family Cookbook'
theme: "github.com/jtom38/hugo-cookbook"
enableEmoji: true

taxonomies:
  tag: 'tags'
  cuisines: 'cuisine'
  courses: 'course'

# Used to bring the /tags/ forward
preserveTaxonomyNames: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  # hugo-cookbook params
  DisplayRssButton: true
  ## This tells the theme to use the list display view
  UseListRows: true

  ## Enable this line to use the card view
  #UseCardView: true