baseURL: 'https://jtom38.github.io/cookbook'
languageCode: 'en-us'
title: 'Cookbook'
theme: "hugo-bulma-cookbook"

taxonomies:
  category: 'categories'
  tag: 'tags'

# Used to bring the /tags/ forward
preserveTaxonomyNames: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5